/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import connectionDB.koneksi;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    
    private Connection conn = new koneksi().connect();
    private DefaultTableModel tabmode;
    private Statement statement;
    
//    public void fasilitas(){
//        try{
//            c1.removeAllItems();
//            String sqlf = "select * from tabelkriteria where kriteria in ('fasilitas')";
//            java.sql.Statement stat = conn.createStatement();
//            ResultSet hasil = stat.executeQuery(sqlf);
//            while(hasil.next()){
//                c1.addItem(hasil.getString("keterangan"));
//            }
//            hasil.last();
//            int jumlahdata = hasil.getRow();
//            hasil.first();
//        }catch(Exception e){
//        }
//    }
//    
//    public void ruangan(){
//        try{
//            c2.removeAllItems();
//            String sqlr = "select * from tabelkriteria where kriteria in ('ruangan')";
//            java.sql.Statement stat = conn.createStatement();
//            ResultSet hasil = stat.executeQuery(sqlr);
//            while(hasil.next()){
//                c2.addItem(hasil.getString("keterangan"));
//            }
//            hasil.last();
//            int jumlahdata = hasil.getRow();
//            hasil.first();
//        }catch(Exception e){
//        }
//    }
    
    protected void kosongkriteria(){
        idkriteria.setText("");
        kriteria.setSelectedIndex(0);
        keterangan.setText("");
        nilai.setSelectedIndex(0);
    }
    
    protected void datatable6(){
    Object [] Baris = {"ID","KRITERA","KETERANGAN","NILAI"};
    tabmode = new DefaultTableModel(null, Baris);
    tabelkriteria.setModel(tabmode);            
    try {
    String sql = "Select * from tabelkriteria";
    
        java.sql.Statement stat = conn.createStatement();
        ResultSet hasil = stat.executeQuery(sql);
        while (hasil.next()){
            String a = hasil.getString("id");
            String b = hasil.getString("kriteria");
            String c = hasil.getString("keterangan");
            String d = hasil.getString("nilai");
            
            String[] data={a,b,c,d};
            tabmode.addRow(data);
        }
    }catch (Exception e){
        }
    }
    
    public MainMenu() {
        initComponents();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        penelutama = new javax.swing.JPanel();
        panelmenu = new javax.swing.JPanel();
        bkriteria = new javax.swing.JButton();
        bdatahp = new javax.swing.JButton();
        bhasil = new javax.swing.JButton();
        bhasil1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        panelmain = new javax.swing.JPanel();
        panelkriteria = new javax.swing.JPanel();
        labelKodeSupplier7 = new javax.swing.JLabel();
        idkriteria = new javax.swing.JTextField();
        kriteria = new javax.swing.JComboBox<>();
        labelKodeSupplier8 = new javax.swing.JLabel();
        labelKodeSupplier9 = new javax.swing.JLabel();
        keterangan = new javax.swing.JTextField();
        nilai = new javax.swing.JComboBox<>();
        labelKodeSupplier10 = new javax.swing.JLabel();
        btnSimpan1 = new javax.swing.JButton();
        btnHapus1 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        tabelkriteria = new javax.swing.JTable();
        panelhp = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        panelhasil = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        panelinfo = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        penelutama.setBackground(new java.awt.Color(0, 177, 79));

        panelmenu.setBackground(new java.awt.Color(0, 177, 79));
        panelmenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));

        bkriteria.setBackground(new java.awt.Color(255, 255, 255));
        bkriteria.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bkriteria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar2/iconplus.png"))); // NOI18N
        bkriteria.setText("DATA KRITERIA");
        bkriteria.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bkriteria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkriteriaActionPerformed(evt);
            }
        });

        bdatahp.setBackground(new java.awt.Color(255, 255, 255));
        bdatahp.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bdatahp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar2/handphone.png"))); // NOI18N
        bdatahp.setText("DATA HANDPHONE");
        bdatahp.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bdatahp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdatahpActionPerformed(evt);
            }
        });

        bhasil.setBackground(new java.awt.Color(255, 255, 255));
        bhasil.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bhasil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar2/hasil-transformed.png"))); // NOI18N
        bhasil.setText("HASIL");
        bhasil.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bhasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhasilActionPerformed(evt);
            }
        });

        bhasil1.setBackground(new java.awt.Color(255, 255, 255));
        bhasil1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bhasil1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar2/tentang-transformed.png"))); // NOI18N
        bhasil1.setText("INFO APLIKASI");
        bhasil1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bhasil1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhasil1ActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar2/logo ojol.jpeg"))); // NOI18N

        javax.swing.GroupLayout panelmenuLayout = new javax.swing.GroupLayout(panelmenu);
        panelmenu.setLayout(panelmenuLayout);
        panelmenuLayout.setHorizontalGroup(
            panelmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelmenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bdatahp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bhasil, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bkriteria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bhasil1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelmenuLayout.setVerticalGroup(
            panelmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelmenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(bkriteria, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bdatahp, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bhasil, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(bhasil1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        panelmain.setBackground(new java.awt.Color(0, 177, 79));
        panelmain.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        panelmain.setLayout(new java.awt.CardLayout());

        panelkriteria.setBackground(new java.awt.Color(0, 177, 79));

        labelKodeSupplier7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelKodeSupplier7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelKodeSupplier7.setText("ID");
        labelKodeSupplier7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        kriteria.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        kriteria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chipset", "RAM" }));

        labelKodeSupplier8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelKodeSupplier8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelKodeSupplier8.setText("KRITERIA");
        labelKodeSupplier8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        labelKodeSupplier9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelKodeSupplier9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelKodeSupplier9.setText("KETERANGAN");
        labelKodeSupplier9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        nilai.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nilai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));

        labelKodeSupplier10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelKodeSupplier10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelKodeSupplier10.setText("NILAI");
        labelKodeSupplier10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnSimpan1.setBackground(new java.awt.Color(255, 255, 255));
        btnSimpan1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSimpan1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar2/save-30-w11.png"))); // NOI18N
        btnSimpan1.setText("Simpan");
        btnSimpan1.setContentAreaFilled(false);
        btnSimpan1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSimpan1.setIconTextGap(0);
        btnSimpan1.setOpaque(true);
        btnSimpan1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSimpan1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSimpan1MouseExited(evt);
            }
        });
        btnSimpan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpan1ActionPerformed(evt);
            }
        });

        btnHapus1.setBackground(new java.awt.Color(255, 255, 255));
        btnHapus1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnHapus1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar2/delete-30-w11.png"))); // NOI18N
        btnHapus1.setText("Hapus");
        btnHapus1.setContentAreaFilled(false);
        btnHapus1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHapus1.setIconTextGap(0);
        btnHapus1.setOpaque(true);
        btnHapus1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHapus1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHapus1MouseExited(evt);
            }
        });
        btnHapus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapus1ActionPerformed(evt);
            }
        });

        tabelkriteria.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tabelkriteria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        tabelkriteria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tabelkriteria.setRowHeight(30);
        tabelkriteria.setRowMargin(2);
        tabelkriteria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelkriteriaMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tabelkriteria);

        javax.swing.GroupLayout panelkriteriaLayout = new javax.swing.GroupLayout(panelkriteria);
        panelkriteria.setLayout(panelkriteriaLayout);
        panelkriteriaLayout.setHorizontalGroup(
            panelkriteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelkriteriaLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(panelkriteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSimpan1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelkriteriaLayout.createSequentialGroup()
                        .addGroup(panelkriteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelKodeSupplier8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelKodeSupplier7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelKodeSupplier9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelKodeSupplier10, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelkriteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnHapus1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelkriteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(keterangan, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(idkriteria, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(kriteria, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(nilai, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelkriteriaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelkriteriaLayout.setVerticalGroup(
            panelkriteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelkriteriaLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(panelkriteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelKodeSupplier7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idkriteria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelkriteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelKodeSupplier8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kriteria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelkriteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelKodeSupplier9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(keterangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(panelkriteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelKodeSupplier10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nilai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(panelkriteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapus1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addGap(46, 46, 46))
        );

        panelmain.add(panelkriteria, "card2");

        panelhp.setBackground(new java.awt.Color(0, 177, 79));

        jLabel2.setText("DATA HANDPHONE");

        javax.swing.GroupLayout panelhpLayout = new javax.swing.GroupLayout(panelhp);
        panelhp.setLayout(panelhpLayout);
        panelhpLayout.setHorizontalGroup(
            panelhpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelhpLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 485, Short.MAX_VALUE))
        );
        panelhpLayout.setVerticalGroup(
            panelhpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelhpLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 414, Short.MAX_VALUE))
        );

        panelmain.add(panelhp, "card3");

        panelhasil.setBackground(new java.awt.Color(0, 177, 79));

        jLabel3.setText("HASIL");

        javax.swing.GroupLayout panelhasilLayout = new javax.swing.GroupLayout(panelhasil);
        panelhasil.setLayout(panelhasilLayout);
        panelhasilLayout.setHorizontalGroup(
            panelhasilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelhasilLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 485, Short.MAX_VALUE))
        );
        panelhasilLayout.setVerticalGroup(
            panelhasilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelhasilLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 414, Short.MAX_VALUE))
        );

        panelmain.add(panelhasil, "card4");

        panelinfo.setBackground(new java.awt.Color(0, 177, 79));

        jLabel4.setText("INFO");

        javax.swing.GroupLayout panelinfoLayout = new javax.swing.GroupLayout(panelinfo);
        panelinfo.setLayout(panelinfoLayout);
        panelinfoLayout.setHorizontalGroup(
            panelinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelinfoLayout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 485, Short.MAX_VALUE))
        );
        panelinfoLayout.setVerticalGroup(
            panelinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelinfoLayout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 414, Short.MAX_VALUE))
        );

        panelmain.add(panelinfo, "card5");

        javax.swing.GroupLayout penelutamaLayout = new javax.swing.GroupLayout(penelutama);
        penelutama.setLayout(penelutamaLayout);
        penelutamaLayout.setHorizontalGroup(
            penelutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(penelutamaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelmenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelmain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        penelutamaLayout.setVerticalGroup(
            penelutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, penelutamaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(penelutamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelmain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelmenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(penelutama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(penelutama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bdatahpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdatahpActionPerformed
        // TODO add your handling code here:
        panelmain.removeAll();
        panelmain.repaint();
        panelmain.revalidate();
        //add panel
        panelmain.add(panelhp);
        panelmain.repaint();
        panelmain.revalidate();
    }//GEN-LAST:event_bdatahpActionPerformed

    private void bhasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhasilActionPerformed
        // TODO add your handling code here:
        panelmain.removeAll();
        panelmain.repaint();
        panelmain.revalidate();
        //add panel
        panelmain.add(panelhasil);
        panelmain.repaint();
        panelmain.revalidate();
    }//GEN-LAST:event_bhasilActionPerformed

    private void bkriteriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkriteriaActionPerformed
        // TODO add your handling code here:
        panelmain.removeAll();
        panelmain.repaint();
        panelmain.revalidate();
        //add panel
        panelmain.add(panelkriteria);
        panelmain.repaint();
        panelmain.revalidate();
    }//GEN-LAST:event_bkriteriaActionPerformed

    private void bhasil1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhasil1ActionPerformed
        // TODO add your handling code here:
        panelmain.removeAll();
        panelmain.repaint();
        panelmain.revalidate();
        //add panel
        panelmain.add(panelinfo);
        panelmain.repaint();
        panelmain.revalidate();
    }//GEN-LAST:event_bhasil1ActionPerformed

    private void btnSimpan1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimpan1MouseEntered
        btnSimpan1.setBackground(new Color(0,0,204));
        btnSimpan1.setForeground(Color.white);
    }//GEN-LAST:event_btnSimpan1MouseEntered

    private void btnSimpan1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimpan1MouseExited
        btnSimpan1.setBackground(new Color(204,204,204));
        btnSimpan1.setForeground(Color.black);
    }//GEN-LAST:event_btnSimpan1MouseExited

    private void btnSimpan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpan1ActionPerformed
        String sql = "insert into tabelkriteria values (?,?,?,?)";
        try{
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, idkriteria.getText());
            stat.setString(2, kriteria.getSelectedItem().toString());
            stat.setString(3, keterangan.getText());
            stat.setString(4, nilai.getSelectedItem().toString());

            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
            kosongkriteria();
            idkriteria.requestFocus();
            datatable6();
//            fasilitas();
//            ruangan();

        }catch (SQLException e){
            JOptionPane.showMessageDialog(null, "Data Gagal Disimpan"+e);
        }
    }//GEN-LAST:event_btnSimpan1ActionPerformed

    private void btnHapus1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHapus1MouseEntered
        btnHapus1.setBackground(new Color(0,0,204));
        btnHapus1.setForeground(Color.white);
    }//GEN-LAST:event_btnHapus1MouseEntered

    private void btnHapus1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHapus1MouseExited
        btnHapus1.setBackground(new Color(204,204,204));
        btnHapus1.setForeground(Color.black);
    }//GEN-LAST:event_btnHapus1MouseExited

    private void btnHapus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapus1ActionPerformed
        int ok = JOptionPane.showConfirmDialog(null,"hapus","Konfirmasi Dialog", JOptionPane.YES_NO_CANCEL_OPTION);
        if (ok==0){
            String sql="delete from tabelkriteria where id='"+idkriteria.getText()+"'";
            try {
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "data berhasil dihapus");
                kosongkriteria();
                idkriteria.requestFocus();
                datatable6();
//                fasilitas();
//                ruangan();
            }catch (SQLException e){
                JOptionPane.showMessageDialog(null, "Data gagal dihapus"+e);
            }
        }
    }//GEN-LAST:event_btnHapus1ActionPerformed

    private void tabelkriteriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelkriteriaMouseClicked
        int bar = tabelkriteria.getSelectedRow();
        String a = tabmode.getValueAt (bar, 0).toString();
        String b = tabmode.getValueAt (bar, 1).toString();
        String c = tabmode.getValueAt (bar, 2).toString();
        String d = tabmode.getValueAt (bar, 3).toString();

        idkriteria.setText(a);
        kriteria.setSelectedItem(b);
        keterangan.setText(c);
        nilai.setSelectedItem(d);
    }//GEN-LAST:event_tabelkriteriaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bdatahp;
    private javax.swing.JButton bhasil;
    private javax.swing.JButton bhasil1;
    private javax.swing.JButton bkriteria;
    private javax.swing.JButton btnHapus1;
    private javax.swing.JButton btnSimpan1;
    private javax.swing.JTextField idkriteria;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextField keterangan;
    private javax.swing.JComboBox<String> kriteria;
    private javax.swing.JLabel labelKodeSupplier10;
    private javax.swing.JLabel labelKodeSupplier7;
    private javax.swing.JLabel labelKodeSupplier8;
    private javax.swing.JLabel labelKodeSupplier9;
    private javax.swing.JComboBox<String> nilai;
    private javax.swing.JPanel panelhasil;
    private javax.swing.JPanel panelhp;
    private javax.swing.JPanel panelinfo;
    private javax.swing.JPanel panelkriteria;
    private javax.swing.JPanel panelmain;
    private javax.swing.JPanel panelmenu;
    private javax.swing.JPanel penelutama;
    private javax.swing.JTable tabelkriteria;
    // End of variables declaration//GEN-END:variables
}
